# Site settings
title: The Mapbox Vision SDK
email: dev@ocupop.com
description: 'A revolutionary viewport for drivers and developers. Connected cameras, intelligent navigation, augmented reality, and high-performance computer vision combine through the Mapbox Vision SDK.'
url: "https://vision.mapbox.com"
permalink: pretty

share_image: /visionsdk-1200x630.png

# Build settings
safe: false
source: src

plugins:
  - jekyll-sitemap